# The ZEN API provides python classes to call ZEN API services.
# Copyright 2025 Carl Zeiss Microscopy GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To obtain a commercial version please contact Carl Zeiss Microscopy GmbH.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zen_api/lm/hardware/v2/camera_service.proto, zen_api/lm/hardware/v2/filter_data.proto, zen_api/lm/hardware/v2/filter_wheel_service.proto, zen_api/lm/hardware/v2/focus_service.proto, zen_api/lm/hardware/v2/get_camera_data.proto, zen_api/lm/hardware/v2/objective_changer_immersion_types.proto, zen_api/lm/hardware/v2/objective_changer_service.proto, zen_api/lm/hardware/v2/objective_data.proto, zen_api/lm/hardware/v2/optovar_data.proto, zen_api/lm/hardware/v2/optovar_service.proto, zen_api/lm/hardware/v2/reflector_changer_service.proto, zen_api/lm/hardware/v2/reflector_data.proto, zen_api/lm/hardware/v2/set_camera_data.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ....common import v1 as ___common_v1__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ObjectiveChangerImmersionTypes(betterproto.Enum):
    """Immersion types to match ObjectiveImmersionTypes"""

    UNSPECIFIED = 0
    """Unspecified"""

    AIR = 1
    """Air"""

    WATER = 2
    """Water"""

    OIL = 4
    """Oil"""

    GLYCERINE = 8
    """Glycerin"""

    SILICONE = 16
    """Silicone"""

    HIOIL = 32
    """HI Oil"""

    POLYOL = 64
    """Polyol"""


@dataclass(eq=False, repr=False)
class GetCameraData(betterproto.Message):
    """Describes a camera."""

    name: str = betterproto.string_field(1)
    """The Name."""

    id: str = betterproto.string_field(2)
    """The Id."""

    is_preset: bool = betterproto.bool_field(3)
    """A value indicating whether the camera is preset."""

    exposure_time: float = betterproto.double_field(4)
    """The ExposureTime."""

    min_exposure_time: float = betterproto.double_field(5)
    """The MinExposureTime."""

    max_exposure_time: float = betterproto.double_field(6)
    """The MaxExposureTime."""

    binning: int = betterproto.int32_field(7)
    """The Binning."""

    binning_description: str = betterproto.string_field(8)
    """The BinningDescription."""

    available_binnings: List[str] = betterproto.string_field(9)
    """The AvailableBinnings."""

    frame: "___common_v1__.DoubleFrame" = betterproto.message_field(10)
    """The Frame."""

    max_frame_size: "___common_v1__.DoubleSize" = betterproto.message_field(11)
    """The MaxFrameWidth."""


@dataclass(eq=False, repr=False)
class SetCameraData(betterproto.Message):
    """Describes the info needed to set a camera."""

    id: str = betterproto.string_field(1)
    """The Id."""

    exposure_time: float = betterproto.double_field(2)
    """The ExposureTime."""

    binning: int = betterproto.int32_field(3)
    """The Binning."""

    frame: "___common_v1__.DoubleFrame" = betterproto.message_field(10)
    """The Frame."""


@dataclass(eq=False, repr=False)
class CameraServiceConfigureCameraRequest(betterproto.Message):
    """The CameraServiceConfigureCameraRequest class."""

    data: "SetCameraData" = betterproto.message_field(1)
    """New configuration data."""


@dataclass(eq=False, repr=False)
class CameraServiceConfigureCameraResponse(betterproto.Message):
    """Describes the result of a configure camera request."""

    pass


@dataclass(eq=False, repr=False)
class CameraServiceGetAllCamerasResponse(betterproto.Message):
    """A list of available cameras."""

    cameras: List["GetCameraData"] = betterproto.message_field(1)
    """The cameras."""


@dataclass(eq=False, repr=False)
class CameraServiceGetCameraRequest(betterproto.Message):
    """The CameraServiceGetCameraRequest class."""

    id: str = betterproto.string_field(1)
    """Id of the camera."""


@dataclass(eq=False, repr=False)
class CameraServiceGetCameraResponse(betterproto.Message):
    """Position index of the camera."""

    camera: "GetCameraData" = betterproto.message_field(1)
    """The position index."""


@dataclass(eq=False, repr=False)
class CameraServiceGetCamerasRequest(betterproto.Message):
    """The CameraServiceGetCamerasRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FilterData(betterproto.Message):
    """Describes a filter."""

    name: str = betterproto.string_field(1)
    """The name/ id of the filter."""

    id: str = betterproto.string_field(2)
    """The id."""

    is_present: bool = betterproto.bool_field(3)
    """A value indicating whether the filter is present."""

    position: int = betterproto.int32_field(4)
    """The position index, starting at 1."""


@dataclass(eq=False, repr=False)
class FilterWheelServiceGetFiltersRequest(betterproto.Message):
    """The FilterWheelServiceGetFiltersRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FilterWheelServiceGetFiltersResponse(betterproto.Message):
    """A list of available filters."""

    filters: List["FilterData"] = betterproto.message_field(1)
    """The filters."""


@dataclass(eq=False, repr=False)
class FilterWheelServiceGetPositionRequest(betterproto.Message):
    """The FilterWheelServiceGetPositionRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FilterWheelServiceGetPositionResponse(betterproto.Message):
    """Position index of the filter wheel."""

    value: int = betterproto.int32_field(1)
    """The position index."""


@dataclass(eq=False, repr=False)
class FilterWheelServiceMoveToRequest(betterproto.Message):
    """The FilterWheelServiceMoveToRequest class."""

    position_index: int = betterproto.int32_field(1)
    """New position index."""


@dataclass(eq=False, repr=False)
class FilterWheelServiceMoveToResponse(betterproto.Message):
    """Describes the result of a filter wheel MoveTo request."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetAccelerationRequest(betterproto.Message):
    """The FocusServiceGetAccelerationRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetAccelerationResponse(betterproto.Message):
    """Acceleration of the focus in %."""

    value: float = betterproto.double_field(1)
    """The acceleration in %."""


@dataclass(eq=False, repr=False)
class FocusServiceGetPositionRequest(betterproto.Message):
    """The FocusServiceGetPositionRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetPositionResponse(betterproto.Message):
    """Position of the focus in meters."""

    value: float = betterproto.double_field(1)
    """The position in meters."""


@dataclass(eq=False, repr=False)
class FocusServiceGetSpeedRequest(betterproto.Message):
    """The FocusServiceGetSpeedRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetSpeedResponse(betterproto.Message):
    """Speed of the focus in %."""

    value: float = betterproto.double_field(1)
    """The speed in %."""


@dataclass(eq=False, repr=False)
class FocusServiceMoveToRequest(betterproto.Message):
    """The FocusServiceMoveToRequest class."""

    value: float = betterproto.double_field(1)
    """New position in meters."""


@dataclass(eq=False, repr=False)
class FocusServiceMoveToResponse(betterproto.Message):
    """Describes the result of a Focus.MoveTo request."""

    position_changed: bool = betterproto.bool_field(1)
    """A value indicating whether the position was changed."""


@dataclass(eq=False, repr=False)
class FocusServiceSetAccelerationRequest(betterproto.Message):
    """The FocusServiceSetAccelerationRequest class."""

    acceleration: float = betterproto.double_field(1)
    """Acceleration in percent, i.e. values from range [0;100]."""


@dataclass(eq=False, repr=False)
class FocusServiceSetAccelerationResponse(betterproto.Message):
    """The FocusServiceSetAccelerationResponse class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceSetSpeedRequest(betterproto.Message):
    """The FocusServiceSetSpeedRequest class."""

    speed: float = betterproto.double_field(1)
    """Speed in percent, i.e. values from range [0;100]."""


@dataclass(eq=False, repr=False)
class FocusServiceSetSpeedResponse(betterproto.Message):
    """The FocusServiceSetSpeedResponse class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceStopRequest(betterproto.Message):
    """The FocusServiceStopRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceStopResponse(betterproto.Message):
    """The FocusServiceStopResponse class."""

    pass


@dataclass(eq=False, repr=False)
class ObjectiveData(betterproto.Message):
    """Describes an objective."""

    name: str = betterproto.string_field(1)
    """The name."""

    na: float = betterproto.double_field(2)
    """The Numerical Apperture."""

    immersion_type: "ObjectiveChangerImmersionTypes" = betterproto.enum_field(3)
    """The immersion type."""

    magnification: float = betterproto.double_field(4)
    """The magnification."""

    position: int = betterproto.int32_field(5)
    """The position index."""


@dataclass(eq=False, repr=False)
class ObjectiveChangerServiceGetObjectivesRequest(betterproto.Message):
    """The ObjectiveChangerServiceGetObjectivesRequest class."""

    pass


@dataclass(eq=False, repr=False)
class ObjectiveChangerServiceGetObjectivesResponse(betterproto.Message):
    """A list of available objectives."""

    objectives: List["ObjectiveData"] = betterproto.message_field(1)
    """The objectives."""


@dataclass(eq=False, repr=False)
class ObjectiveChangerServiceGetPositionRequest(betterproto.Message):
    """The ObjectiveChangerServiceGetPositionRequest class."""

    pass


@dataclass(eq=False, repr=False)
class ObjectiveChangerServiceGetPositionResponse(betterproto.Message):
    """Position index of the objective."""

    value: int = betterproto.int32_field(1)
    """The position index."""


@dataclass(eq=False, repr=False)
class ObjectiveChangerServiceMoveToRequest(betterproto.Message):
    """The ObjectiveChangerServiceMoveToRequest class."""

    position_index: int = betterproto.int32_field(1)
    """New position index."""


@dataclass(eq=False, repr=False)
class ObjectiveChangerServiceMoveToResponse(betterproto.Message):
    """Describes the result of a ObjectiveChanger.MoveTo request."""

    pass


@dataclass(eq=False, repr=False)
class OptovarData(betterproto.Message):
    """Describes an optovar."""

    name: str = betterproto.string_field(1)
    """The name."""

    magnification: float = betterproto.double_field(2)
    """The magnification."""

    position: int = betterproto.int32_field(3)
    """The position index."""


@dataclass(eq=False, repr=False)
class OptovarServiceGetOptovarsRequest(betterproto.Message):
    """The OptovarServiceGetOptovarsRequest class."""

    pass


@dataclass(eq=False, repr=False)
class OptovarServiceGetOptovarsResponse(betterproto.Message):
    """A list of available optovars."""

    optovars: List["OptovarData"] = betterproto.message_field(1)
    """The optovars."""


@dataclass(eq=False, repr=False)
class OptovarServiceGetPositionRequest(betterproto.Message):
    """The OptovarServiceGetPositionRequest class."""

    pass


@dataclass(eq=False, repr=False)
class OptovarServiceGetPositionResponse(betterproto.Message):
    """Position index of the optovar."""

    value: int = betterproto.int32_field(1)
    """The position index."""


@dataclass(eq=False, repr=False)
class OptovarServiceMoveToRequest(betterproto.Message):
    """The OptovarServiceMoveToRequest class."""

    position_index: int = betterproto.int32_field(1)
    """New position index."""


@dataclass(eq=False, repr=False)
class OptovarServiceMoveToResponse(betterproto.Message):
    """Describes the result of a Optovar.MoveTo request."""

    pass


@dataclass(eq=False, repr=False)
class ReflectorData(betterproto.Message):
    """Describes a reflector."""

    name: str = betterproto.string_field(1)
    """The name."""

    position: int = betterproto.int32_field(2)
    """The position index."""


@dataclass(eq=False, repr=False)
class ReflectorChangerServiceGetPositionRequest(betterproto.Message):
    """The ReflectorChangerServiceGetPositionRequest class."""

    pass


@dataclass(eq=False, repr=False)
class ReflectorChangerServiceGetPositionResponse(betterproto.Message):
    """Position index of the objective."""

    value: int = betterproto.int32_field(1)
    """The position index."""


@dataclass(eq=False, repr=False)
class ReflectorChangerServiceGetReflectorsRequest(betterproto.Message):
    """The ReflectorChangerServiceGetReflectorsRequest class."""

    pass


@dataclass(eq=False, repr=False)
class ReflectorChangerServiceGetReflectorsResponse(betterproto.Message):
    """A list of available objectives."""

    reflectors: List["ReflectorData"] = betterproto.message_field(1)
    """The objectives."""


@dataclass(eq=False, repr=False)
class ReflectorChangerServiceMoveToRequest(betterproto.Message):
    """The ReflectorChangerServiceMoveToRequest class."""

    position_index: int = betterproto.int32_field(1)
    """New position index."""


@dataclass(eq=False, repr=False)
class ReflectorChangerServiceMoveToResponse(betterproto.Message):
    """Describes the result of a ReflectorChanger.MoveTo request."""

    pass


class CameraServiceStub(betterproto.ServiceStub):
    async def configure_camera(
        self,
        camera_service_configure_camera_request: "CameraServiceConfigureCameraRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CameraServiceConfigureCameraResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.CameraService/ConfigureCamera",
            camera_service_configure_camera_request,
            CameraServiceConfigureCameraResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_camera(
        self,
        camera_service_get_camera_request: "CameraServiceGetCameraRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CameraServiceGetCameraResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.CameraService/GetCamera",
            camera_service_get_camera_request,
            CameraServiceGetCameraResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_cameras(
        self,
        camera_service_get_cameras_request: "CameraServiceGetCamerasRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CameraServiceGetAllCamerasResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.CameraService/GetCameras",
            camera_service_get_cameras_request,
            CameraServiceGetAllCamerasResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class FilterWheelServiceStub(betterproto.ServiceStub):
    async def get_filters(
        self,
        filter_wheel_service_get_filters_request: "FilterWheelServiceGetFiltersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FilterWheelServiceGetFiltersResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FilterWheelService/GetFilters",
            filter_wheel_service_get_filters_request,
            FilterWheelServiceGetFiltersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_position(
        self,
        filter_wheel_service_get_position_request: "FilterWheelServiceGetPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FilterWheelServiceGetPositionResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FilterWheelService/GetPosition",
            filter_wheel_service_get_position_request,
            FilterWheelServiceGetPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to(
        self,
        filter_wheel_service_move_to_request: "FilterWheelServiceMoveToRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FilterWheelServiceMoveToResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FilterWheelService/MoveTo",
            filter_wheel_service_move_to_request,
            FilterWheelServiceMoveToResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class FocusServiceStub(betterproto.ServiceStub):
    async def get_acceleration(
        self,
        focus_service_get_acceleration_request: "FocusServiceGetAccelerationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceGetAccelerationResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/GetAcceleration",
            focus_service_get_acceleration_request,
            FocusServiceGetAccelerationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_position(
        self,
        focus_service_get_position_request: "FocusServiceGetPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceGetPositionResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/GetPosition",
            focus_service_get_position_request,
            FocusServiceGetPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_speed(
        self,
        focus_service_get_speed_request: "FocusServiceGetSpeedRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceGetSpeedResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/GetSpeed",
            focus_service_get_speed_request,
            FocusServiceGetSpeedResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to(
        self,
        focus_service_move_to_request: "FocusServiceMoveToRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceMoveToResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/MoveTo",
            focus_service_move_to_request,
            FocusServiceMoveToResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_acceleration(
        self,
        focus_service_set_acceleration_request: "FocusServiceSetAccelerationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceSetAccelerationResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/SetAcceleration",
            focus_service_set_acceleration_request,
            FocusServiceSetAccelerationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_speed(
        self,
        focus_service_set_speed_request: "FocusServiceSetSpeedRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceSetSpeedResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/SetSpeed",
            focus_service_set_speed_request,
            FocusServiceSetSpeedResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop(
        self,
        focus_service_stop_request: "FocusServiceStopRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceStopResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.FocusService/Stop",
            focus_service_stop_request,
            FocusServiceStopResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ObjectiveChangerServiceStub(betterproto.ServiceStub):
    async def get_objectives(
        self,
        objective_changer_service_get_objectives_request: "ObjectiveChangerServiceGetObjectivesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ObjectiveChangerServiceGetObjectivesResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.ObjectiveChangerService/GetObjectives",
            objective_changer_service_get_objectives_request,
            ObjectiveChangerServiceGetObjectivesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_position(
        self,
        objective_changer_service_get_position_request: "ObjectiveChangerServiceGetPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ObjectiveChangerServiceGetPositionResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.ObjectiveChangerService/GetPosition",
            objective_changer_service_get_position_request,
            ObjectiveChangerServiceGetPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to(
        self,
        objective_changer_service_move_to_request: "ObjectiveChangerServiceMoveToRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ObjectiveChangerServiceMoveToResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.ObjectiveChangerService/MoveTo",
            objective_changer_service_move_to_request,
            ObjectiveChangerServiceMoveToResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OptovarServiceStub(betterproto.ServiceStub):
    async def get_optovars(
        self,
        optovar_service_get_optovars_request: "OptovarServiceGetOptovarsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OptovarServiceGetOptovarsResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.OptovarService/GetOptovars",
            optovar_service_get_optovars_request,
            OptovarServiceGetOptovarsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_position(
        self,
        optovar_service_get_position_request: "OptovarServiceGetPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OptovarServiceGetPositionResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.OptovarService/GetPosition",
            optovar_service_get_position_request,
            OptovarServiceGetPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to(
        self,
        optovar_service_move_to_request: "OptovarServiceMoveToRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OptovarServiceMoveToResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.OptovarService/MoveTo",
            optovar_service_move_to_request,
            OptovarServiceMoveToResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ReflectorChangerServiceStub(betterproto.ServiceStub):
    async def get_position(
        self,
        reflector_changer_service_get_position_request: "ReflectorChangerServiceGetPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ReflectorChangerServiceGetPositionResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.ReflectorChangerService/GetPosition",
            reflector_changer_service_get_position_request,
            ReflectorChangerServiceGetPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_reflectors(
        self,
        reflector_changer_service_get_reflectors_request: "ReflectorChangerServiceGetReflectorsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ReflectorChangerServiceGetReflectorsResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.ReflectorChangerService/GetReflectors",
            reflector_changer_service_get_reflectors_request,
            ReflectorChangerServiceGetReflectorsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to(
        self,
        reflector_changer_service_move_to_request: "ReflectorChangerServiceMoveToRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ReflectorChangerServiceMoveToResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v2.ReflectorChangerService/MoveTo",
            reflector_changer_service_move_to_request,
            ReflectorChangerServiceMoveToResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class CameraServiceBase(ServiceBase):

    async def configure_camera(
        self,
        camera_service_configure_camera_request: "CameraServiceConfigureCameraRequest",
    ) -> "CameraServiceConfigureCameraResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_camera(
        self, camera_service_get_camera_request: "CameraServiceGetCameraRequest"
    ) -> "CameraServiceGetCameraResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_cameras(
        self, camera_service_get_cameras_request: "CameraServiceGetCamerasRequest"
    ) -> "CameraServiceGetAllCamerasResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_configure_camera(
        self,
        stream: "grpclib.server.Stream[CameraServiceConfigureCameraRequest, CameraServiceConfigureCameraResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.configure_camera(request)
        await stream.send_message(response)

    async def __rpc_get_camera(
        self,
        stream: "grpclib.server.Stream[CameraServiceGetCameraRequest, CameraServiceGetCameraResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_camera(request)
        await stream.send_message(response)

    async def __rpc_get_cameras(
        self,
        stream: "grpclib.server.Stream[CameraServiceGetCamerasRequest, CameraServiceGetAllCamerasResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_cameras(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v2.CameraService/ConfigureCamera": grpclib.const.Handler(
                self.__rpc_configure_camera,
                grpclib.const.Cardinality.UNARY_UNARY,
                CameraServiceConfigureCameraRequest,
                CameraServiceConfigureCameraResponse,
            ),
            "/zen_api.lm.hardware.v2.CameraService/GetCamera": grpclib.const.Handler(
                self.__rpc_get_camera,
                grpclib.const.Cardinality.UNARY_UNARY,
                CameraServiceGetCameraRequest,
                CameraServiceGetCameraResponse,
            ),
            "/zen_api.lm.hardware.v2.CameraService/GetCameras": grpclib.const.Handler(
                self.__rpc_get_cameras,
                grpclib.const.Cardinality.UNARY_UNARY,
                CameraServiceGetCamerasRequest,
                CameraServiceGetAllCamerasResponse,
            ),
        }


class FilterWheelServiceBase(ServiceBase):

    async def get_filters(
        self,
        filter_wheel_service_get_filters_request: "FilterWheelServiceGetFiltersRequest",
    ) -> "FilterWheelServiceGetFiltersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_position(
        self,
        filter_wheel_service_get_position_request: "FilterWheelServiceGetPositionRequest",
    ) -> "FilterWheelServiceGetPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to(
        self, filter_wheel_service_move_to_request: "FilterWheelServiceMoveToRequest"
    ) -> "FilterWheelServiceMoveToResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_filters(
        self,
        stream: "grpclib.server.Stream[FilterWheelServiceGetFiltersRequest, FilterWheelServiceGetFiltersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_filters(request)
        await stream.send_message(response)

    async def __rpc_get_position(
        self,
        stream: "grpclib.server.Stream[FilterWheelServiceGetPositionRequest, FilterWheelServiceGetPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_position(request)
        await stream.send_message(response)

    async def __rpc_move_to(
        self,
        stream: "grpclib.server.Stream[FilterWheelServiceMoveToRequest, FilterWheelServiceMoveToResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v2.FilterWheelService/GetFilters": grpclib.const.Handler(
                self.__rpc_get_filters,
                grpclib.const.Cardinality.UNARY_UNARY,
                FilterWheelServiceGetFiltersRequest,
                FilterWheelServiceGetFiltersResponse,
            ),
            "/zen_api.lm.hardware.v2.FilterWheelService/GetPosition": grpclib.const.Handler(
                self.__rpc_get_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                FilterWheelServiceGetPositionRequest,
                FilterWheelServiceGetPositionResponse,
            ),
            "/zen_api.lm.hardware.v2.FilterWheelService/MoveTo": grpclib.const.Handler(
                self.__rpc_move_to,
                grpclib.const.Cardinality.UNARY_UNARY,
                FilterWheelServiceMoveToRequest,
                FilterWheelServiceMoveToResponse,
            ),
        }


class FocusServiceBase(ServiceBase):

    async def get_acceleration(
        self,
        focus_service_get_acceleration_request: "FocusServiceGetAccelerationRequest",
    ) -> "FocusServiceGetAccelerationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_position(
        self, focus_service_get_position_request: "FocusServiceGetPositionRequest"
    ) -> "FocusServiceGetPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_speed(
        self, focus_service_get_speed_request: "FocusServiceGetSpeedRequest"
    ) -> "FocusServiceGetSpeedResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to(
        self, focus_service_move_to_request: "FocusServiceMoveToRequest"
    ) -> "FocusServiceMoveToResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_acceleration(
        self,
        focus_service_set_acceleration_request: "FocusServiceSetAccelerationRequest",
    ) -> "FocusServiceSetAccelerationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_speed(
        self, focus_service_set_speed_request: "FocusServiceSetSpeedRequest"
    ) -> "FocusServiceSetSpeedResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def stop(
        self, focus_service_stop_request: "FocusServiceStopRequest"
    ) -> "FocusServiceStopResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_acceleration(
        self,
        stream: "grpclib.server.Stream[FocusServiceGetAccelerationRequest, FocusServiceGetAccelerationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_acceleration(request)
        await stream.send_message(response)

    async def __rpc_get_position(
        self,
        stream: "grpclib.server.Stream[FocusServiceGetPositionRequest, FocusServiceGetPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_position(request)
        await stream.send_message(response)

    async def __rpc_get_speed(
        self,
        stream: "grpclib.server.Stream[FocusServiceGetSpeedRequest, FocusServiceGetSpeedResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_speed(request)
        await stream.send_message(response)

    async def __rpc_move_to(
        self,
        stream: "grpclib.server.Stream[FocusServiceMoveToRequest, FocusServiceMoveToResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to(request)
        await stream.send_message(response)

    async def __rpc_set_acceleration(
        self,
        stream: "grpclib.server.Stream[FocusServiceSetAccelerationRequest, FocusServiceSetAccelerationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_acceleration(request)
        await stream.send_message(response)

    async def __rpc_set_speed(
        self,
        stream: "grpclib.server.Stream[FocusServiceSetSpeedRequest, FocusServiceSetSpeedResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_speed(request)
        await stream.send_message(response)

    async def __rpc_stop(
        self,
        stream: "grpclib.server.Stream[FocusServiceStopRequest, FocusServiceStopResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.stop(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v2.FocusService/GetAcceleration": grpclib.const.Handler(
                self.__rpc_get_acceleration,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceGetAccelerationRequest,
                FocusServiceGetAccelerationResponse,
            ),
            "/zen_api.lm.hardware.v2.FocusService/GetPosition": grpclib.const.Handler(
                self.__rpc_get_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceGetPositionRequest,
                FocusServiceGetPositionResponse,
            ),
            "/zen_api.lm.hardware.v2.FocusService/GetSpeed": grpclib.const.Handler(
                self.__rpc_get_speed,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceGetSpeedRequest,
                FocusServiceGetSpeedResponse,
            ),
            "/zen_api.lm.hardware.v2.FocusService/MoveTo": grpclib.const.Handler(
                self.__rpc_move_to,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceMoveToRequest,
                FocusServiceMoveToResponse,
            ),
            "/zen_api.lm.hardware.v2.FocusService/SetAcceleration": grpclib.const.Handler(
                self.__rpc_set_acceleration,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceSetAccelerationRequest,
                FocusServiceSetAccelerationResponse,
            ),
            "/zen_api.lm.hardware.v2.FocusService/SetSpeed": grpclib.const.Handler(
                self.__rpc_set_speed,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceSetSpeedRequest,
                FocusServiceSetSpeedResponse,
            ),
            "/zen_api.lm.hardware.v2.FocusService/Stop": grpclib.const.Handler(
                self.__rpc_stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceStopRequest,
                FocusServiceStopResponse,
            ),
        }


class ObjectiveChangerServiceBase(ServiceBase):

    async def get_objectives(
        self,
        objective_changer_service_get_objectives_request: "ObjectiveChangerServiceGetObjectivesRequest",
    ) -> "ObjectiveChangerServiceGetObjectivesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_position(
        self,
        objective_changer_service_get_position_request: "ObjectiveChangerServiceGetPositionRequest",
    ) -> "ObjectiveChangerServiceGetPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to(
        self,
        objective_changer_service_move_to_request: "ObjectiveChangerServiceMoveToRequest",
    ) -> "ObjectiveChangerServiceMoveToResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_objectives(
        self,
        stream: "grpclib.server.Stream[ObjectiveChangerServiceGetObjectivesRequest, ObjectiveChangerServiceGetObjectivesResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_objectives(request)
        await stream.send_message(response)

    async def __rpc_get_position(
        self,
        stream: "grpclib.server.Stream[ObjectiveChangerServiceGetPositionRequest, ObjectiveChangerServiceGetPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_position(request)
        await stream.send_message(response)

    async def __rpc_move_to(
        self,
        stream: "grpclib.server.Stream[ObjectiveChangerServiceMoveToRequest, ObjectiveChangerServiceMoveToResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v2.ObjectiveChangerService/GetObjectives": grpclib.const.Handler(
                self.__rpc_get_objectives,
                grpclib.const.Cardinality.UNARY_UNARY,
                ObjectiveChangerServiceGetObjectivesRequest,
                ObjectiveChangerServiceGetObjectivesResponse,
            ),
            "/zen_api.lm.hardware.v2.ObjectiveChangerService/GetPosition": grpclib.const.Handler(
                self.__rpc_get_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                ObjectiveChangerServiceGetPositionRequest,
                ObjectiveChangerServiceGetPositionResponse,
            ),
            "/zen_api.lm.hardware.v2.ObjectiveChangerService/MoveTo": grpclib.const.Handler(
                self.__rpc_move_to,
                grpclib.const.Cardinality.UNARY_UNARY,
                ObjectiveChangerServiceMoveToRequest,
                ObjectiveChangerServiceMoveToResponse,
            ),
        }


class OptovarServiceBase(ServiceBase):

    async def get_optovars(
        self, optovar_service_get_optovars_request: "OptovarServiceGetOptovarsRequest"
    ) -> "OptovarServiceGetOptovarsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_position(
        self, optovar_service_get_position_request: "OptovarServiceGetPositionRequest"
    ) -> "OptovarServiceGetPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to(
        self, optovar_service_move_to_request: "OptovarServiceMoveToRequest"
    ) -> "OptovarServiceMoveToResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_optovars(
        self,
        stream: "grpclib.server.Stream[OptovarServiceGetOptovarsRequest, OptovarServiceGetOptovarsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_optovars(request)
        await stream.send_message(response)

    async def __rpc_get_position(
        self,
        stream: "grpclib.server.Stream[OptovarServiceGetPositionRequest, OptovarServiceGetPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_position(request)
        await stream.send_message(response)

    async def __rpc_move_to(
        self,
        stream: "grpclib.server.Stream[OptovarServiceMoveToRequest, OptovarServiceMoveToResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v2.OptovarService/GetOptovars": grpclib.const.Handler(
                self.__rpc_get_optovars,
                grpclib.const.Cardinality.UNARY_UNARY,
                OptovarServiceGetOptovarsRequest,
                OptovarServiceGetOptovarsResponse,
            ),
            "/zen_api.lm.hardware.v2.OptovarService/GetPosition": grpclib.const.Handler(
                self.__rpc_get_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                OptovarServiceGetPositionRequest,
                OptovarServiceGetPositionResponse,
            ),
            "/zen_api.lm.hardware.v2.OptovarService/MoveTo": grpclib.const.Handler(
                self.__rpc_move_to,
                grpclib.const.Cardinality.UNARY_UNARY,
                OptovarServiceMoveToRequest,
                OptovarServiceMoveToResponse,
            ),
        }


class ReflectorChangerServiceBase(ServiceBase):

    async def get_position(
        self,
        reflector_changer_service_get_position_request: "ReflectorChangerServiceGetPositionRequest",
    ) -> "ReflectorChangerServiceGetPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_reflectors(
        self,
        reflector_changer_service_get_reflectors_request: "ReflectorChangerServiceGetReflectorsRequest",
    ) -> "ReflectorChangerServiceGetReflectorsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to(
        self,
        reflector_changer_service_move_to_request: "ReflectorChangerServiceMoveToRequest",
    ) -> "ReflectorChangerServiceMoveToResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_position(
        self,
        stream: "grpclib.server.Stream[ReflectorChangerServiceGetPositionRequest, ReflectorChangerServiceGetPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_position(request)
        await stream.send_message(response)

    async def __rpc_get_reflectors(
        self,
        stream: "grpclib.server.Stream[ReflectorChangerServiceGetReflectorsRequest, ReflectorChangerServiceGetReflectorsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_reflectors(request)
        await stream.send_message(response)

    async def __rpc_move_to(
        self,
        stream: "grpclib.server.Stream[ReflectorChangerServiceMoveToRequest, ReflectorChangerServiceMoveToResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v2.ReflectorChangerService/GetPosition": grpclib.const.Handler(
                self.__rpc_get_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                ReflectorChangerServiceGetPositionRequest,
                ReflectorChangerServiceGetPositionResponse,
            ),
            "/zen_api.lm.hardware.v2.ReflectorChangerService/GetReflectors": grpclib.const.Handler(
                self.__rpc_get_reflectors,
                grpclib.const.Cardinality.UNARY_UNARY,
                ReflectorChangerServiceGetReflectorsRequest,
                ReflectorChangerServiceGetReflectorsResponse,
            ),
            "/zen_api.lm.hardware.v2.ReflectorChangerService/MoveTo": grpclib.const.Handler(
                self.__rpc_move_to,
                grpclib.const.Cardinality.UNARY_UNARY,
                ReflectorChangerServiceMoveToRequest,
                ReflectorChangerServiceMoveToResponse,
            ),
        }
