# The ZEN API provides python classes to call ZEN API services.
# Copyright 2025 Carl Zeiss Microscopy GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To obtain a commercial version please contact Carl Zeiss Microscopy GmbH.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zen_api/common/v1/double_point.proto, zen_api/common/v1/int_point.proto, zen_api/common/v1/int_size.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class IntPoint(betterproto.Message):
    """Integer-based point."""

    x: int = betterproto.int32_field(1)
    """The coordinate X of a point."""

    y: int = betterproto.int32_field(2)
    """The coordinate Y of a point."""


@dataclass(eq=False, repr=False)
class IntSize(betterproto.Message):
    """Integer-based size."""

    width: int = betterproto.int32_field(1)
    """The width."""

    height: int = betterproto.int32_field(2)
    """The height."""


@dataclass(eq=False, repr=False)
class DoublePoint(betterproto.Message):
    """Double-based point object."""

    x: float = betterproto.double_field(1)
    """The coordinate X of a point."""

    y: float = betterproto.double_field(2)
    """The coordinate Y of a point."""
