# The ZEN API provides python classes to call ZEN API services.
# Copyright 2025 Carl Zeiss Microscopy GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To obtain a commercial version please contact Carl Zeiss Microscopy GmbH.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zen_api/lm/hardware/v1/configured_container_info.proto, zen_api/lm/hardware/v1/focus_service.proto, zen_api/lm/hardware/v1/sample_carrier_service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class ConfiguredContainerInfo(betterproto.Message):
    """
    Contains the information about a configured container in an experiment.
    """

    container_name: str = betterproto.string_field(1)
    """The name of the container (e.g., "B1")."""

    is_activated: bool = betterproto.bool_field(2)
    """A value indicating whether the container is activated or not."""


@dataclass(eq=False, repr=False)
class FocusServiceGetAccelerationRequest(betterproto.Message):
    """The FocusServiceGetAccelerationRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetAccelerationResponse(betterproto.Message):
    """Acceleration of the focus in %."""

    value: float = betterproto.double_field(1)
    """The acceleration in %."""


@dataclass(eq=False, repr=False)
class FocusServiceGetPositionRequest(betterproto.Message):
    """The FocusServiceGetPositionRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetPositionResponse(betterproto.Message):
    """Position of the focus in µm."""

    value: float = betterproto.double_field(1)
    """The position in µm."""


@dataclass(eq=False, repr=False)
class FocusServiceGetSpeedRequest(betterproto.Message):
    """The FocusServiceGetSpeedRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceGetSpeedResponse(betterproto.Message):
    """Speed of the focus in %."""

    value: float = betterproto.double_field(1)
    """The speed in %."""


@dataclass(eq=False, repr=False)
class FocusServiceMoveToRequest(betterproto.Message):
    """The FocusServiceMoveToRequest class."""

    value: float = betterproto.double_field(1)
    """New position in µm."""


@dataclass(eq=False, repr=False)
class FocusServiceMoveToResponse(betterproto.Message):
    """Describes the result of a Focus.MoveTo request."""

    position_changed: bool = betterproto.bool_field(1)
    """A value indicating whether the position was changed."""


@dataclass(eq=False, repr=False)
class FocusServiceSetAccelerationRequest(betterproto.Message):
    """The FocusServiceSetAccelerationRequest class."""

    acceleration: float = betterproto.double_field(1)
    """Acceleration in percent, i.e. values from range [0;100]."""


@dataclass(eq=False, repr=False)
class FocusServiceSetAccelerationResponse(betterproto.Message):
    """The FocusServiceSetAccelerationResponse class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceSetSpeedRequest(betterproto.Message):
    """The FocusServiceSetSpeedRequest class."""

    speed: float = betterproto.double_field(1)
    """Speed in percent, i.e. values from range [0;100]."""


@dataclass(eq=False, repr=False)
class FocusServiceSetSpeedResponse(betterproto.Message):
    """The FocusServiceSetSpeedResponse class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceStopRequest(betterproto.Message):
    """The FocusServiceStopRequest class."""

    pass


@dataclass(eq=False, repr=False)
class FocusServiceStopResponse(betterproto.Message):
    """The FocusServiceStopResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceActivateContainerRangeRequest(betterproto.Message):
    """The SampleCarrierServiceActivateContainerRangeRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""

    start_container_name: str = betterproto.string_field(2)
    """Name of the container where the range starts (e.g., "C3")."""

    end_container_name: str = betterproto.string_field(3)
    """Name of the container where the range ends (e.g., "D8")."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceActivateContainerRangeResponse(betterproto.Message):
    """The SampleCarrierServiceActivateContainerRangeResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceActivateContainerRequest(betterproto.Message):
    """The SampleCarrierServiceActivateContainerRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""

    container_name: str = betterproto.string_field(2)
    """Name of the container (e.g., "B1")."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceActivateContainerResponse(betterproto.Message):
    """The SampleCarrierServiceActivateContainerResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceActivateContainersRequest(betterproto.Message):
    """The SampleCarrierServiceActivateContainersRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""

    container_names: List[str] = betterproto.string_field(2)
    """Names of the containers (e.g., ["A1", "A2", "B7"])."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceActivateContainersResponse(betterproto.Message):
    """The SampleCarrierServiceActivateContainersResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceDeactivateContainerRangeRequest(betterproto.Message):
    """The SampleCarrierServiceDeactivateContainerRangeRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""

    start_container_name: str = betterproto.string_field(2)
    """Name of the container where the range starts (e.g., "C3")."""

    end_container_name: str = betterproto.string_field(3)
    """Name of the container where the range ends (e.g., "D8")."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceDeactivateContainerRangeResponse(betterproto.Message):
    """The SampleCarrierServiceDeactivateContainerRangeResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceDeactivateContainerRequest(betterproto.Message):
    """The SampleCarrierServiceDeactivateContainerRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""

    container_name: str = betterproto.string_field(2)
    """Name of the container (e.g., "B1")."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceDeactivateContainerResponse(betterproto.Message):
    """The SampleCarrierServiceDeactivateContainerResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceDeactivateContainersRequest(betterproto.Message):
    """The SampleCarrierServiceDeactivateContainersRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""

    container_names: List[str] = betterproto.string_field(2)
    """Names of the containers (e.g., ["A1", "A2", "B7"])."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceDeactivateContainersResponse(betterproto.Message):
    """The SampleCarrierServiceDeactivateContainersResponse class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceGetConfiguredContainersRequest(betterproto.Message):
    """The SampleCarrierServiceGetConfiguredContainersRequest class."""

    experiment_id: str = betterproto.string_field(1)
    """Experiment ID."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceGetConfiguredContainersResponse(betterproto.Message):
    """
    Contains the information about the configured containers in an experiment.
    """

    configured_containers: List["ConfiguredContainerInfo"] = betterproto.message_field(
        1
    )
    """The information about the configured containers in an experiment."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceGetCurrentContainerRequest(betterproto.Message):
    """The SampleCarrierServiceGetCurrentContainerRequest class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceGetCurrentContainerResponse(betterproto.Message):
    """
    Contains the information in which container of the sample carrier the stage is positioned at.
    """

    row_index: int = betterproto.int32_field(1)
    """
    The row index of the container in the sample carrier (starts with index 0).
    """

    column_index: int = betterproto.int32_field(2)
    """
    The column index of the container in the sample carrier (starts with index 0).
    """


@dataclass(eq=False, repr=False)
class SampleCarrierServiceGetInfoRequest(betterproto.Message):
    """The SampleCarrierServiceGetInfoRequest class."""

    pass


@dataclass(eq=False, repr=False)
class SampleCarrierServiceGetInfoResponse(betterproto.Message):
    """Contains the sample carrier information."""

    rows: int = betterproto.int32_field(1)
    """The number of rows in the sample carrier."""

    columns: int = betterproto.int32_field(2)
    """The number of columns in the sample carrier."""

    name: str = betterproto.string_field(3)
    """The name of the sample carrier."""

    material: str = betterproto.string_field(4)
    """The bottom material which is used for this sample carrier."""

    thickness: float = betterproto.double_field(5)
    """The bottom thickness of this sample carrier (in meters)."""

    skirt: float = betterproto.double_field(6)
    """The skirt (i.e. bottom offset) of this sample carrier (in meters)."""

    refractive_index: float = betterproto.double_field(7)
    """The refractive index of the bottom material of this sample carrier."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceMoveToContainerRequest(betterproto.Message):
    """The SampleCarrierServiceMoveToContainerRequest class."""

    row_index: int = betterproto.int32_field(1)
    """The row index of the container (starts with index 0)."""

    column_index: int = betterproto.int32_field(2)
    """The column index of the container (starts with index 0)."""


@dataclass(eq=False, repr=False)
class SampleCarrierServiceMoveToContainerResponse(betterproto.Message):
    """The SampleCarrierServiceMoveToContainerResponse class."""

    pass


class FocusServiceStub(betterproto.ServiceStub):
    async def get_acceleration(
        self,
        focus_service_get_acceleration_request: "FocusServiceGetAccelerationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceGetAccelerationResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/GetAcceleration",
            focus_service_get_acceleration_request,
            FocusServiceGetAccelerationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_position(
        self,
        focus_service_get_position_request: "FocusServiceGetPositionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceGetPositionResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/GetPosition",
            focus_service_get_position_request,
            FocusServiceGetPositionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_speed(
        self,
        focus_service_get_speed_request: "FocusServiceGetSpeedRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceGetSpeedResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/GetSpeed",
            focus_service_get_speed_request,
            FocusServiceGetSpeedResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to(
        self,
        focus_service_move_to_request: "FocusServiceMoveToRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceMoveToResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/MoveTo",
            focus_service_move_to_request,
            FocusServiceMoveToResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_acceleration(
        self,
        focus_service_set_acceleration_request: "FocusServiceSetAccelerationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceSetAccelerationResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/SetAcceleration",
            focus_service_set_acceleration_request,
            FocusServiceSetAccelerationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_speed(
        self,
        focus_service_set_speed_request: "FocusServiceSetSpeedRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceSetSpeedResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/SetSpeed",
            focus_service_set_speed_request,
            FocusServiceSetSpeedResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop(
        self,
        focus_service_stop_request: "FocusServiceStopRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FocusServiceStopResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.FocusService/Stop",
            focus_service_stop_request,
            FocusServiceStopResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SampleCarrierServiceStub(betterproto.ServiceStub):
    async def activate_container(
        self,
        sample_carrier_service_activate_container_request: "SampleCarrierServiceActivateContainerRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceActivateContainerResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/ActivateContainer",
            sample_carrier_service_activate_container_request,
            SampleCarrierServiceActivateContainerResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def activate_container_range(
        self,
        sample_carrier_service_activate_container_range_request: "SampleCarrierServiceActivateContainerRangeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceActivateContainerRangeResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/ActivateContainerRange",
            sample_carrier_service_activate_container_range_request,
            SampleCarrierServiceActivateContainerRangeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def activate_containers(
        self,
        sample_carrier_service_activate_containers_request: "SampleCarrierServiceActivateContainersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceActivateContainersResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/ActivateContainers",
            sample_carrier_service_activate_containers_request,
            SampleCarrierServiceActivateContainersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def deactivate_container(
        self,
        sample_carrier_service_deactivate_container_request: "SampleCarrierServiceDeactivateContainerRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceDeactivateContainerResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/DeactivateContainer",
            sample_carrier_service_deactivate_container_request,
            SampleCarrierServiceDeactivateContainerResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def deactivate_container_range(
        self,
        sample_carrier_service_deactivate_container_range_request: "SampleCarrierServiceDeactivateContainerRangeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceDeactivateContainerRangeResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/DeactivateContainerRange",
            sample_carrier_service_deactivate_container_range_request,
            SampleCarrierServiceDeactivateContainerRangeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def deactivate_containers(
        self,
        sample_carrier_service_deactivate_containers_request: "SampleCarrierServiceDeactivateContainersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceDeactivateContainersResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/DeactivateContainers",
            sample_carrier_service_deactivate_containers_request,
            SampleCarrierServiceDeactivateContainersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_configured_containers(
        self,
        sample_carrier_service_get_configured_containers_request: "SampleCarrierServiceGetConfiguredContainersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceGetConfiguredContainersResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/GetConfiguredContainers",
            sample_carrier_service_get_configured_containers_request,
            SampleCarrierServiceGetConfiguredContainersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_current_container(
        self,
        sample_carrier_service_get_current_container_request: "SampleCarrierServiceGetCurrentContainerRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceGetCurrentContainerResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/GetCurrentContainer",
            sample_carrier_service_get_current_container_request,
            SampleCarrierServiceGetCurrentContainerResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_info(
        self,
        sample_carrier_service_get_info_request: "SampleCarrierServiceGetInfoRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceGetInfoResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/GetInfo",
            sample_carrier_service_get_info_request,
            SampleCarrierServiceGetInfoResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to_container(
        self,
        sample_carrier_service_move_to_container_request: "SampleCarrierServiceMoveToContainerRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SampleCarrierServiceMoveToContainerResponse":
        return await self._unary_unary(
            "/zen_api.lm.hardware.v1.SampleCarrierService/MoveToContainer",
            sample_carrier_service_move_to_container_request,
            SampleCarrierServiceMoveToContainerResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class FocusServiceBase(ServiceBase):

    async def get_acceleration(
        self,
        focus_service_get_acceleration_request: "FocusServiceGetAccelerationRequest",
    ) -> "FocusServiceGetAccelerationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_position(
        self, focus_service_get_position_request: "FocusServiceGetPositionRequest"
    ) -> "FocusServiceGetPositionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_speed(
        self, focus_service_get_speed_request: "FocusServiceGetSpeedRequest"
    ) -> "FocusServiceGetSpeedResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to(
        self, focus_service_move_to_request: "FocusServiceMoveToRequest"
    ) -> "FocusServiceMoveToResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_acceleration(
        self,
        focus_service_set_acceleration_request: "FocusServiceSetAccelerationRequest",
    ) -> "FocusServiceSetAccelerationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_speed(
        self, focus_service_set_speed_request: "FocusServiceSetSpeedRequest"
    ) -> "FocusServiceSetSpeedResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def stop(
        self, focus_service_stop_request: "FocusServiceStopRequest"
    ) -> "FocusServiceStopResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_acceleration(
        self,
        stream: "grpclib.server.Stream[FocusServiceGetAccelerationRequest, FocusServiceGetAccelerationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_acceleration(request)
        await stream.send_message(response)

    async def __rpc_get_position(
        self,
        stream: "grpclib.server.Stream[FocusServiceGetPositionRequest, FocusServiceGetPositionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_position(request)
        await stream.send_message(response)

    async def __rpc_get_speed(
        self,
        stream: "grpclib.server.Stream[FocusServiceGetSpeedRequest, FocusServiceGetSpeedResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_speed(request)
        await stream.send_message(response)

    async def __rpc_move_to(
        self,
        stream: "grpclib.server.Stream[FocusServiceMoveToRequest, FocusServiceMoveToResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to(request)
        await stream.send_message(response)

    async def __rpc_set_acceleration(
        self,
        stream: "grpclib.server.Stream[FocusServiceSetAccelerationRequest, FocusServiceSetAccelerationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_acceleration(request)
        await stream.send_message(response)

    async def __rpc_set_speed(
        self,
        stream: "grpclib.server.Stream[FocusServiceSetSpeedRequest, FocusServiceSetSpeedResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_speed(request)
        await stream.send_message(response)

    async def __rpc_stop(
        self,
        stream: "grpclib.server.Stream[FocusServiceStopRequest, FocusServiceStopResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.stop(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v1.FocusService/GetAcceleration": grpclib.const.Handler(
                self.__rpc_get_acceleration,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceGetAccelerationRequest,
                FocusServiceGetAccelerationResponse,
            ),
            "/zen_api.lm.hardware.v1.FocusService/GetPosition": grpclib.const.Handler(
                self.__rpc_get_position,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceGetPositionRequest,
                FocusServiceGetPositionResponse,
            ),
            "/zen_api.lm.hardware.v1.FocusService/GetSpeed": grpclib.const.Handler(
                self.__rpc_get_speed,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceGetSpeedRequest,
                FocusServiceGetSpeedResponse,
            ),
            "/zen_api.lm.hardware.v1.FocusService/MoveTo": grpclib.const.Handler(
                self.__rpc_move_to,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceMoveToRequest,
                FocusServiceMoveToResponse,
            ),
            "/zen_api.lm.hardware.v1.FocusService/SetAcceleration": grpclib.const.Handler(
                self.__rpc_set_acceleration,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceSetAccelerationRequest,
                FocusServiceSetAccelerationResponse,
            ),
            "/zen_api.lm.hardware.v1.FocusService/SetSpeed": grpclib.const.Handler(
                self.__rpc_set_speed,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceSetSpeedRequest,
                FocusServiceSetSpeedResponse,
            ),
            "/zen_api.lm.hardware.v1.FocusService/Stop": grpclib.const.Handler(
                self.__rpc_stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusServiceStopRequest,
                FocusServiceStopResponse,
            ),
        }


class SampleCarrierServiceBase(ServiceBase):

    async def activate_container(
        self,
        sample_carrier_service_activate_container_request: "SampleCarrierServiceActivateContainerRequest",
    ) -> "SampleCarrierServiceActivateContainerResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def activate_container_range(
        self,
        sample_carrier_service_activate_container_range_request: "SampleCarrierServiceActivateContainerRangeRequest",
    ) -> "SampleCarrierServiceActivateContainerRangeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def activate_containers(
        self,
        sample_carrier_service_activate_containers_request: "SampleCarrierServiceActivateContainersRequest",
    ) -> "SampleCarrierServiceActivateContainersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deactivate_container(
        self,
        sample_carrier_service_deactivate_container_request: "SampleCarrierServiceDeactivateContainerRequest",
    ) -> "SampleCarrierServiceDeactivateContainerResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deactivate_container_range(
        self,
        sample_carrier_service_deactivate_container_range_request: "SampleCarrierServiceDeactivateContainerRangeRequest",
    ) -> "SampleCarrierServiceDeactivateContainerRangeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deactivate_containers(
        self,
        sample_carrier_service_deactivate_containers_request: "SampleCarrierServiceDeactivateContainersRequest",
    ) -> "SampleCarrierServiceDeactivateContainersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_configured_containers(
        self,
        sample_carrier_service_get_configured_containers_request: "SampleCarrierServiceGetConfiguredContainersRequest",
    ) -> "SampleCarrierServiceGetConfiguredContainersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_current_container(
        self,
        sample_carrier_service_get_current_container_request: "SampleCarrierServiceGetCurrentContainerRequest",
    ) -> "SampleCarrierServiceGetCurrentContainerResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_info(
        self,
        sample_carrier_service_get_info_request: "SampleCarrierServiceGetInfoRequest",
    ) -> "SampleCarrierServiceGetInfoResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to_container(
        self,
        sample_carrier_service_move_to_container_request: "SampleCarrierServiceMoveToContainerRequest",
    ) -> "SampleCarrierServiceMoveToContainerResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_activate_container(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceActivateContainerRequest, SampleCarrierServiceActivateContainerResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.activate_container(request)
        await stream.send_message(response)

    async def __rpc_activate_container_range(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceActivateContainerRangeRequest, SampleCarrierServiceActivateContainerRangeResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.activate_container_range(request)
        await stream.send_message(response)

    async def __rpc_activate_containers(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceActivateContainersRequest, SampleCarrierServiceActivateContainersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.activate_containers(request)
        await stream.send_message(response)

    async def __rpc_deactivate_container(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceDeactivateContainerRequest, SampleCarrierServiceDeactivateContainerResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.deactivate_container(request)
        await stream.send_message(response)

    async def __rpc_deactivate_container_range(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceDeactivateContainerRangeRequest, SampleCarrierServiceDeactivateContainerRangeResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.deactivate_container_range(request)
        await stream.send_message(response)

    async def __rpc_deactivate_containers(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceDeactivateContainersRequest, SampleCarrierServiceDeactivateContainersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.deactivate_containers(request)
        await stream.send_message(response)

    async def __rpc_get_configured_containers(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceGetConfiguredContainersRequest, SampleCarrierServiceGetConfiguredContainersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_configured_containers(request)
        await stream.send_message(response)

    async def __rpc_get_current_container(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceGetCurrentContainerRequest, SampleCarrierServiceGetCurrentContainerResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_current_container(request)
        await stream.send_message(response)

    async def __rpc_get_info(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceGetInfoRequest, SampleCarrierServiceGetInfoResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_info(request)
        await stream.send_message(response)

    async def __rpc_move_to_container(
        self,
        stream: "grpclib.server.Stream[SampleCarrierServiceMoveToContainerRequest, SampleCarrierServiceMoveToContainerResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to_container(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.hardware.v1.SampleCarrierService/ActivateContainer": grpclib.const.Handler(
                self.__rpc_activate_container,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceActivateContainerRequest,
                SampleCarrierServiceActivateContainerResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/ActivateContainerRange": grpclib.const.Handler(
                self.__rpc_activate_container_range,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceActivateContainerRangeRequest,
                SampleCarrierServiceActivateContainerRangeResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/ActivateContainers": grpclib.const.Handler(
                self.__rpc_activate_containers,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceActivateContainersRequest,
                SampleCarrierServiceActivateContainersResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/DeactivateContainer": grpclib.const.Handler(
                self.__rpc_deactivate_container,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceDeactivateContainerRequest,
                SampleCarrierServiceDeactivateContainerResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/DeactivateContainerRange": grpclib.const.Handler(
                self.__rpc_deactivate_container_range,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceDeactivateContainerRangeRequest,
                SampleCarrierServiceDeactivateContainerRangeResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/DeactivateContainers": grpclib.const.Handler(
                self.__rpc_deactivate_containers,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceDeactivateContainersRequest,
                SampleCarrierServiceDeactivateContainersResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/GetConfiguredContainers": grpclib.const.Handler(
                self.__rpc_get_configured_containers,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceGetConfiguredContainersRequest,
                SampleCarrierServiceGetConfiguredContainersResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/GetCurrentContainer": grpclib.const.Handler(
                self.__rpc_get_current_container,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceGetCurrentContainerRequest,
                SampleCarrierServiceGetCurrentContainerResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/GetInfo": grpclib.const.Handler(
                self.__rpc_get_info,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceGetInfoRequest,
                SampleCarrierServiceGetInfoResponse,
            ),
            "/zen_api.lm.hardware.v1.SampleCarrierService/MoveToContainer": grpclib.const.Handler(
                self.__rpc_move_to_container,
                grpclib.const.Cardinality.UNARY_UNARY,
                SampleCarrierServiceMoveToContainerRequest,
                SampleCarrierServiceMoveToContainerResponse,
            ),
        }
