# The ZEN API provides python classes to call ZEN API services.
# Copyright 2025 Carl Zeiss Microscopy GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To obtain a commercial version please contact Carl Zeiss Microscopy GmbH.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zen_api/workflows/v1/start_job_options.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class StartJobOptions(betterproto.Message):
    """Start Job options."""

    result_path: str = betterproto.string_field(1)
    """
    A value indicating a path for saving a Job results in the file system.
     -- If value is given than Job output will be copied to given path in filesystem and not uploaded to ZEN Archive.
     Have to be in the Windows-supported directory path format (local drive or network share).
     -- If value is null (or empty/whitespace) than Job output will be uploaded to ZEN Archive and not copied to anywhere.
    """
