# The ZEN API provides python classes to call ZEN API services.
# Copyright 2025 Carl Zeiss Microscopy GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To obtain a commercial version please contact Carl Zeiss Microscopy GmbH.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: zen_api/lm/live_scan/v1/live_scan_service.proto, zen_api/lm/live_scan/v1/live_scan_service_configuration.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class LiveScanServiceConfiguration(betterproto.Message):
    """Response object representing the configuration."""

    sample_holder_template: str = betterproto.string_field(1)
    """Gets  the type template."""

    live_scan_detection: bool = betterproto.bool_field(2)
    """Gets  a value indicating whether sample carrier detection is active."""

    measure_bottom_thickness: bool = betterproto.bool_field(3)
    """
    Gets  a value indicating whether bottom thickness has to be measured.
    """

    determine_bottom_material: bool = betterproto.bool_field(4)
    """
    Gets  a value indicating whether bottom material determination is active.
    """

    create_carrier_overview: bool = betterproto.bool_field(5)
    """Gets  a value indicating whether sample carrier detection is active."""

    read_barcodes: bool = betterproto.bool_field(6)
    """Gets  a value indicating whether barcodes must be read."""

    use_left_barcode: bool = betterproto.bool_field(7)
    """Gets  a value indicating whether the left barcode must be read."""

    use_right_barcode: bool = betterproto.bool_field(8)
    """Gets  a value indicating whether the right barcode must be read."""

    automatic_live_scan_calibration: bool = betterproto.bool_field(9)
    """
    Gets  a value indicating whether automatic sample carrier calibration is active.
    """

    refractive_index: float = betterproto.double_field(10)
    """The refractive index of the bottom material of this sample carrier."""

    material: str = betterproto.string_field(11)
    """The bottom material of this sample carrier."""


@dataclass(eq=False, repr=False)
class LiveScanServiceEjectTrayRequest(betterproto.Message):
    """The LiveScanServiceEjectTrayRequest class."""

    pass


@dataclass(eq=False, repr=False)
class LiveScanServiceEjectTrayResponse(betterproto.Message):
    """Empty response upon ejecting the tray."""

    notifications: List[str] = betterproto.string_field(1)
    """The list of notifications."""


@dataclass(eq=False, repr=False)
class LiveScanServiceGetConfigurationRequest(betterproto.Message):
    """The LiveScanServiceGetConfigurationRequest class."""

    pass


@dataclass(eq=False, repr=False)
class LiveScanServiceGetConfigurationResponse(betterproto.Message):
    """Request for getting the configuration."""

    config: "LiveScanServiceConfiguration" = betterproto.message_field(1)
    """Configuration."""


@dataclass(eq=False, repr=False)
class LiveScanServiceLoadTrayAndPrescanRequest(betterproto.Message):
    """The LiveScanServiceLoadTrayAndPrescanRequest class."""

    pass


@dataclass(eq=False, repr=False)
class LiveScanServiceLoadTrayAndPrescanResponse(betterproto.Message):
    """Empty response upon loading the tray."""

    notifications: List[str] = betterproto.string_field(1)
    """The list of notifications."""


@dataclass(eq=False, repr=False)
class LiveScanServiceSetConfigurationRequest(betterproto.Message):
    """Request for setting the configuration."""

    config: "LiveScanServiceConfiguration" = betterproto.message_field(1)
    """Configuration."""


@dataclass(eq=False, repr=False)
class LiveScanServiceSetConfigurationResponse(betterproto.Message):
    """Empty response upon setting the configuration."""

    notifications: List[str] = betterproto.string_field(1)
    """The list of notifications."""


class LiveScanServiceStub(betterproto.ServiceStub):
    async def eject_tray(
        self,
        live_scan_service_eject_tray_request: "LiveScanServiceEjectTrayRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "LiveScanServiceEjectTrayResponse":
        return await self._unary_unary(
            "/zen_api.lm.live_scan.v1.LiveScanService/EjectTray",
            live_scan_service_eject_tray_request,
            LiveScanServiceEjectTrayResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_configuration(
        self,
        live_scan_service_get_configuration_request: "LiveScanServiceGetConfigurationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "LiveScanServiceGetConfigurationResponse":
        return await self._unary_unary(
            "/zen_api.lm.live_scan.v1.LiveScanService/GetConfiguration",
            live_scan_service_get_configuration_request,
            LiveScanServiceGetConfigurationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def load_tray_and_prescan(
        self,
        live_scan_service_load_tray_and_prescan_request: "LiveScanServiceLoadTrayAndPrescanRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "LiveScanServiceLoadTrayAndPrescanResponse":
        return await self._unary_unary(
            "/zen_api.lm.live_scan.v1.LiveScanService/LoadTrayAndPrescan",
            live_scan_service_load_tray_and_prescan_request,
            LiveScanServiceLoadTrayAndPrescanResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_configuration(
        self,
        live_scan_service_set_configuration_request: "LiveScanServiceSetConfigurationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "LiveScanServiceSetConfigurationResponse":
        return await self._unary_unary(
            "/zen_api.lm.live_scan.v1.LiveScanService/SetConfiguration",
            live_scan_service_set_configuration_request,
            LiveScanServiceSetConfigurationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class LiveScanServiceBase(ServiceBase):

    async def eject_tray(
        self, live_scan_service_eject_tray_request: "LiveScanServiceEjectTrayRequest"
    ) -> "LiveScanServiceEjectTrayResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_configuration(
        self,
        live_scan_service_get_configuration_request: "LiveScanServiceGetConfigurationRequest",
    ) -> "LiveScanServiceGetConfigurationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def load_tray_and_prescan(
        self,
        live_scan_service_load_tray_and_prescan_request: "LiveScanServiceLoadTrayAndPrescanRequest",
    ) -> "LiveScanServiceLoadTrayAndPrescanResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_configuration(
        self,
        live_scan_service_set_configuration_request: "LiveScanServiceSetConfigurationRequest",
    ) -> "LiveScanServiceSetConfigurationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_eject_tray(
        self,
        stream: "grpclib.server.Stream[LiveScanServiceEjectTrayRequest, LiveScanServiceEjectTrayResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.eject_tray(request)
        await stream.send_message(response)

    async def __rpc_get_configuration(
        self,
        stream: "grpclib.server.Stream[LiveScanServiceGetConfigurationRequest, LiveScanServiceGetConfigurationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_configuration(request)
        await stream.send_message(response)

    async def __rpc_load_tray_and_prescan(
        self,
        stream: "grpclib.server.Stream[LiveScanServiceLoadTrayAndPrescanRequest, LiveScanServiceLoadTrayAndPrescanResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.load_tray_and_prescan(request)
        await stream.send_message(response)

    async def __rpc_set_configuration(
        self,
        stream: "grpclib.server.Stream[LiveScanServiceSetConfigurationRequest, LiveScanServiceSetConfigurationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_configuration(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/zen_api.lm.live_scan.v1.LiveScanService/EjectTray": grpclib.const.Handler(
                self.__rpc_eject_tray,
                grpclib.const.Cardinality.UNARY_UNARY,
                LiveScanServiceEjectTrayRequest,
                LiveScanServiceEjectTrayResponse,
            ),
            "/zen_api.lm.live_scan.v1.LiveScanService/GetConfiguration": grpclib.const.Handler(
                self.__rpc_get_configuration,
                grpclib.const.Cardinality.UNARY_UNARY,
                LiveScanServiceGetConfigurationRequest,
                LiveScanServiceGetConfigurationResponse,
            ),
            "/zen_api.lm.live_scan.v1.LiveScanService/LoadTrayAndPrescan": grpclib.const.Handler(
                self.__rpc_load_tray_and_prescan,
                grpclib.const.Cardinality.UNARY_UNARY,
                LiveScanServiceLoadTrayAndPrescanRequest,
                LiveScanServiceLoadTrayAndPrescanResponse,
            ),
            "/zen_api.lm.live_scan.v1.LiveScanService/SetConfiguration": grpclib.const.Handler(
                self.__rpc_set_configuration,
                grpclib.const.Cardinality.UNARY_UNARY,
                LiveScanServiceSetConfigurationRequest,
                LiveScanServiceSetConfigurationResponse,
            ),
        }
