# run: conda env create --file conda_env_czmodel.yml
name: czmodel
channels:
  - defaults
dependencies:
  - python=3.8
  - conda
  - pip
  - jupyter
  - matplotlib
  - nb-conda-kernels
  - cudatoolkit=10
  - cudnn
  - scikit-learn

  - pip:
      - czmodel==1.1.0
      - livelossplot

# Create an environment
# conda env create --file conda_env_czmodel.yml

# Update an environment
# conda env update --name czmodel --file conda_env_czmodel.yml --prune

# Remove an environment
# conda remove --name czmodel --all

# Show the locations of all versions of Python that are currently in the path
# Windows: where python
# Linux which -a python
